version: "2"
services:
  zookeeper:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-zookeeper'
    hostname: zookeeper
    volumes:
      - /e/docker/lambo-planet/zookeeper/logs:/datalog
      - /e/docker/lambo-planet/zookeeper/data:/data
  redis:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-redis'
    hostname: redis
    volumes:
      - /e/docker/lambo-planet/redis/data:/data
  mysql:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-mysql'
    hostname: mysql
    volumes:
      - /e/docker/lambo-planet/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  upms-tomcat:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-upms-tomcat'
    hostname: upms-tomcat
    volumes:
      - /e/docker/lambo-planet/upms/tomcat-logs:/usr/local/tomcat/logs
      - /e/docker/lambo-planet/upms/server-logs:/usr/local/logs
    ports:
      - 1111:8080
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - REDIS_SERVER=redis
      - DATABASE_SERVER=mysql
  upms-rpc:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-upms-rpc'
    hostname: upms-rpc
    volumes:
      - /e/docker/lambo-planet/upms/rpc-logs:/usr/local/lambo-upms-rpc-service/logs
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - DATABASE_SERVER=mysql
      - REDIS_SERVER=redis
  nginx:
    image: 'registry.cn-hangzhou.aliyuncs.com/btmagm/lambo-planet-nginx'
    hostname: nginx
    volumes:
      - /e/docker/lambo-planet/nginx/logs:/var/log/nginx
    ports:
      - 80:80
