version: "2"
services:
  zookeeper:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-zookeeper'
    hostname: zookeeper
    volumes:
      - /e/docker/lambo-planet/zookeeper/logs:/datalog
      - /e/docker/lambo-planet/zookeeper/data:/data
    ports:
      - 2181:2181
  redis:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-redis'
    hostname: redis
    volumes:
      - /e/docker/lambo-planet/redis/data:/data
    ports:
      - 6379:6379
  mysql:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-mysql'
    hostname: mysql
    volumes:
      - /e/docker/lambo-planet/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  upms-rpc:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-upms-rpc'
    hostname: upms-rpc
    volumes:
      - /e/docker/lambo-planet/upms/rpc-logs:/usr/local/lambo-upms-rpc-service/logs
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - DATABASE_SERVER=mysql
      - REDIS_SERVER=redis
    depends_on:
        - mysql
        - zookeeper
  upms-tomcat:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-upms-tomcat'
    hostname: upms-tomcat
    volumes:
      - /e/docker/lambo-planet/upms/tomcat-logs:/usr/local/tomcat/logs
      - /e/docker/lambo-planet/upms/server-logs:/usr/local/logs
    ports:
      - 1111:8080
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - REDIS_SERVER=redis
      - DATABASE_SERVER=mysql
    depends_on:
      - upms-rpc
      - zookeeper
      - redis
  nginx:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-nginx'
    hostname: nginx
    volumes:
      - /e/docker/lambo-planet/nginx/logs:/var/log/nginx
      - /e/github/lambo-planet-docker/lambo-planet-nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - upms-tomcat