version: "2"
services:
  zookeeper:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-zookeeper'
    hostname: zookeeper
    privileged: true
    volumes:
      - /e/docker/lambo-planet/zookeeper/logs:/datalog
      - /e/docker/lambo-planet/zookeeper/data:/data
    ports:
      - 2181:2181
  redis:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-redis'
    hostname: redis
    privileged: true
    volumes:
      - /e/docker/lambo-planet/redis/data:/data
    ports:
      - 6379:6379
  mysql:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-mysql'
    hostname: mysql
    privileged: true
    volumes:
      - /e/docker/lambo-planet/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  swift:
      image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-swift'
      hostname: swift
      privileged: true
      volumes:
        - /e/docker/lambo-planet/swift/data:/swift/nodes
      ports:
        - 8091:8080
  upms-rpc:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-upms-rpc'
    hostname: upms-rpc
    privileged: true
    network_mode: "host"
    volumes:
      - /e/docker/lambo-planet/upms/rpc-logs:/usr/local/lambo-upms-rpc-service/logs
    environment:
      - ZOOKEEPER_SERVER=10.10.10.136
      - DATABASE_SERVER=10.10.10.136
      - REDIS_SERVER=10.10.10.136
    depends_on:
        - mysql
        - zookeeper
  upms-tomcat:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-upms-tomcat'
    hostname: upms-tomcat
    privileged: true
    volumes:
      - /e/docker/lambo-planet/upms/tomcat-logs:/usr/local/tomcat/logs
      - /e/docker/lambo-planet/upms/server-logs:/usr/local/logs
    ports:
      - 1111:8080
    environment:
      - ZOOKEEPER_SERVER=10.10.10.136
      - REDIS_SERVER=10.10.10.136
      - DATABASE_SERVER=10.10.10.136
    depends_on:
      - upms-rpc
      - zookeeper
      - redis
  nginx:
    image: 'registry.cn-beijing.aliyuncs.com/btmagm/lambo-planet-nginx'
    hostname: nginx
    privileged: true
    volumes:
      - /e/docker/lambo-planet/nginx/logs:/var/log/nginx
    ports:
      - 83:80
    depends_on:
      - upms-tomcat